# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: npm install
      run: npm install
      
    - name: build
      run: npm run build
      
    - name: deploy
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
    - name: upload to S3
      run: aws s3 sync ./build s3://padak-find-dust
      
    - name: invalidate
      run: aws cloudfront create-invalidation --distribution-id EK22WY6N2AFNK --paths / /index.html /service-worker.js /manifest.json
